-- WARNING USE WITH CAUTION --
-- ======================== --
 -- DROP DATABASE if EXISTS materials;
 -- DROP DATABASE if EXISTS furnitures;
 -- DROP DATABASE if EXISTS categories;
 -- DROP DATABASE if EXISTS conditions;
 -- DROP DATABASE if EXISTS users;
 -- DROP DATABASE if EXISTS furniture_user;
 -- DROP DATABASE if EXISTS roles;
